spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gpais/reactive/tree/master/config/src/main/resources/shared
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/gpais/reactive/tree/master/config/src/main/resources/shared  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

