spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gpais/reactive/tree/master/config/src/main/resources/shared
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/gpais/reactive/tree/master/config/src/main/resources/shared

server:
  port: 8888

