server:
  port: 8081
spring:
  application:
    name: shoppingservice
management:
    context-path: "/"
    security:
        enabled: false
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
      